### ISSUE TITLE
rmi4update v1.3.0+ hangs during EnterFlashProgrammingV7()

### ISSUE THREAD

**Issue by rekanorman** [aduggan/rmi4utils#19]
Hi,

I'm using rmi4update to update the Synaptics touchscreen firmware on a Lenovo 300e 2nd Gen AMD Chromebook. The firmware versions and touchscreen properties are included in the logs below.

Using rmi4update v1.2.14, the update succeeds: [update_logs_1-2-14.txt](https://github.com/aduggan/rmi4utils/files/6439232/update_logs_1-2-14.txt).

Using rmi4update v1.3.0 or higher, the update hangs during EnterFlashProgrammingV7(): [update_logs_1-3-0.txt](https://github.com/aduggan/rmi4utils/files/6439233/update_logs_1-3-0.txt).

I've bisected the breakage to commit https://github.com/aduggan/rmi4utils/commit/8ade3e95a9b6a3c62a0ed152dd952c93a59d96ba.

The updater seems to hang at this call to [ReadF34QueriesV7()](https://github.com/aduggan/rmi4utils/blob/master/rmi4update/rmi4update.cpp#L1138). This call was added as part of commit  https://github.com/aduggan/rmi4utils/commit/8ade3e95a9b6a3c62a0ed152dd952c93a59d96ba, and there are now two calls to ReadF34Queries*() in [EnterFlashProgrammingV7()](https://github.com/aduggan/rmi4utils/blob/master/rmi4update/rmi4update.cpp#L1081). It's not clear whether this is intentional.

If I build v1.3.0 (or later) with that call to ReadF34QueriesV7() removed, then the update succeeds [update_logs_1-3-0_call_removed.txt](https://github.com/aduggan/rmi4utils/files/6439234/update_logs_1-3-0_call_removed.txt).

Do you have any idea why this call is causing the updater to hang?

Thanks,
Reka

**Comment by blueue** [comment]
This issue should be resolved by https://github.com/aduggan/rmi4utils/commit/18b874697a67c8ad82f16ec59e724c078ce466b1

**Comment by rekanorman** [comment]
Thanks!
