### ISSUE TITLE
build break by NDK ndk-r19 - scandir use of undeclared identifier 'versionsort'

### ISSUE THREAD

**Issue by achenYT** [aduggan/rmi4utils#9]
Hi,
I'm using ndk-r19 to build the rmi4utils but I got "scandir use of undeclared identifier 'versionsort'" during the compiling which is at "rmidevice/hiddevice.cpp" line 662.  And I can complete the build after I changed it to "alphasort". Could you help to check it?

Thanks,
Aaron

**Comment by enh-google** [comment]
should be fixed by https://github.com/aduggan/rmi4utils/pull/14
